export const contacts = [
  {
    id: 'user-id-001',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@google.com',
    phone: '+44892418222',
    status: 'Active',
    accounts: [
      {
        id: 'microsoft-us-001',
        name: 'Microsoft US',
        status: 'ACTIVE',
      },
      {
        id: 'google-ca-002',
        name: 'Google Canada',
        status: 'INVITED',
      },
      {
        id: 'amazon-us-003',
        name: 'Amazon US',
        status: 'INACTIVE',
      },
      {
        id: 'meta-emea-004',
        name: 'Meta EMEA',
        status: 'REMOVED',
      },
    ],
  },
  {
    id: 'user-id-002',
    firstName: 'John',
    lastName: 'Smith',
    email: 'john@smith.com',
    phone: '+447777777777',
    status: 'Active',
    accounts: [
      {
        id: 'microsoft-us-001',
        name: 'Microsoft US',
        status: 'ACTIVE',
      },
      {
        id: 'google-ca-002',
        name: 'Google Canada',
        status: 'ACTIVE',
      },
    ],
  },
  {
    id: 'user-id-003',
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.s@yahoo.com',
    phone: '+44867384383',
    status: 'Active',
    accounts: [
      {
        id: 'microsoft-us-001',
        name: 'Microsoft US',
        status: 'ACTIVE',
      },
      {
        id: 'google-ca-002',
        name: 'Google Canada',
        status: 'ACTIVE',
      },
    ],
  },
  {
    id: 'user-id-004',
    firstName: 'Michael',
    lastName: 'Crout',
    email: 'm.crout@gmail.com',
    phone: '+44852741827',
    status: 'Active',
    accounts: [
      {
        id: 'microsoft-us-001',
        name: 'Microsoft US',
        status: 'ACTIVE',
      },
      {
        id: 'google-ca-002',
        name: 'Google Canada',
        status: 'ACTIVE',
      },
    ],
  },
  {
    id: 'user-id-005',
    firstName: 'Brian S.',
    lastName: 'Tropey',
    email: 'briantropey@outlook.com',
    phone: '+44827463923',
    status: 'Active',
    accounts: [
      {
        id: 'microsoft-us-001',
        name: 'Microsoft US',
        status: 'ACTIVE',
      },
      {
        id: 'google-ca-002',
        name: 'Google Canada',
        status: 'ACTIVE',
      },
    ],
  },
  {
    id: 'user-id-006',
    firstName: 'Mary',
    lastName: 'Stewart',
    email: 'mary.stewart@gmail.com',
    phone: '+44837438442',
    status: 'Active',
    accounts: [
      {
        id: 'microsoft-us-001',
        name: 'Microsoft US',
        status: 'ACTIVE',
      },
      {
        id: 'google-ca-002',
        name: 'Google Canada',
        status: 'ACTIVE',
      },
    ],
  },
  {
    id: 'user-id-007',
    firstName: 'Josephina',
    lastName: 'Miller',
    email: 'josephinarmiller@gmail.com',
    phone: '+44837537812',
    status: 'Active',
    accounts: [
      {
        id: 'microsoft-us-001',
        name: 'Microsoft US',
        status: 'ACTIVE',
      },
      {
        id: 'google-ca-002',
        name: 'Google Canada',
        status: 'ACTIVE',
      },
    ],
  },
  {
    id: 'user-id-008',
    firstName: 'James',
    lastName: 'Holmes',
    email: 'j.holmes@yahoo.com',
    phone: '+44853573958',
    status: 'Active',
    accounts: [
      {
        id: 'microsoft-us-001',
        name: 'Microsoft US',
        status: 'ACTIVE',
      },
      {
        id: 'google-ca-002',
        name: 'Google Canada',
        status: 'ACTIVE',
      },
    ],
  },
  {
    id: 'user-id-009',
    firstName: 'Robert',
    lastName: 'Collins',
    email: 'rob.collins@gmail.com',
    phone: '+44384284278',
    status: 'Active',
    accounts: [
      {
        id: 'microsoft-us-001',
        name: 'Microsoft US',
        status: 'ACTIVE',
      },
      {
        id: 'google-ca-002',
        name: 'Google Canada',
        status: 'ACTIVE',
      },
    ],
  },
  {
    id: 'user-id-010',
    firstName: 'Darlene',
    lastName: 'Lucas',
    email: 'darlene.lucas@outlook.com',
    phone: '+44924284287',
    status: 'Active',
    accounts: [
      {
        id: 'microsoft-us-001',
        name: 'Microsoft US',
        status: 'ACTIVE',
      },
      {
        id: 'google-ca-002',
        name: 'Google Canada',
        status: 'ACTIVE',
      },
    ],
  },
  {
    id: 'user-id-011',
    firstName: 'Dorothy',
    lastName: 'Villagomez',
    email: 'dorothyvillagomez@outlook.com',
    phone: '+44981241282',
    status: 'Active',
    accounts: [
      {
        id: 'microsoft-us-001',
        name: 'Microsoft US',
        status: 'ACTIVE',
      },
      {
        id: 'google-ca-002',
        name: 'Google Canada',
        status: 'ACTIVE',
      },
    ],
  },
  {
    id: 'user-id-012',
    firstName: 'Richard',
    lastName: 'Jackson',
    email: 'ricky.jackson@gmail.com',
    phone: '+44772489128',
    status: 'Active',
    accounts: [
      {
        id: 'microsoft-us-001',
        name: 'Microsoft US',
        status: 'ACTIVE',
      },
      {
        id: 'google-ca-002',
        name: 'Google Canada',
        status: 'ACTIVE',
      },
    ],
  },
  {
    id: 'user-id-013',
    firstName: 'Janet',
    lastName: 'Lewis',
    email: 'j.lewis@gmail.com',
    phone: '+44218519222',
    status: 'Active',
    accounts: [
      {
        id: 'microsoft-us-001',
        name: 'Microsoft US',
        status: 'ACTIVE',
      },
      {
        id: 'google-ca-002',
        name: 'Google Canada',
        status: 'ACTIVE',
      },
    ],
  },
  {
    id: 'user-id-014',
    firstName: 'James',
    lastName: 'Smoky',
    email: 'Smoky@smith.com',
    phone: '+443333333333',
    status: 'Active',
    accounts: [
      {
        id: 'microsoft-us-001',
        name: 'Microsoft US',
        status: 'ACTIVE',
      },
      {
        id: 'google-ca-002',
        name: 'Google Canada',
        status: 'ACTIVE',
      },
    ],
  },
  {
  id: 'user-id-015',
  firstName: 'Kevin',
  lastName: 'Walker',
  email: 'kevin.walker@gmail.com',
  phone: '+44781234115',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-016',
  firstName: 'Laura',
  lastName: 'Green',
  email: 'laura.green@gmail.com',
  phone: '+44781234116',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-017',
  firstName: 'Patrick',
  lastName: 'Hill',
  email: 'patrick.hill@gmail.com',
  phone: '+44781234117',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-018',
  firstName: 'Nancy',
  lastName: 'Adams',
  email: 'nancy.adams@gmail.com',
  phone: '+44781234118',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-019',
  firstName: 'George',
  lastName: 'Baker',
  email: 'george.baker@gmail.com',
  phone: '+44781234119',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-020',
  firstName: 'Emma',
  lastName: 'Carter',
  email: 'emma.carter@gmail.com',
  phone: '+44781234120',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-021',
  firstName: 'Henry',
  lastName: 'Phillips',
  email: 'henry.phillips@gmail.com',
  phone: '+44781234121',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-022',
  firstName: 'Olivia',
  lastName: 'Parker',
  email: 'olivia.parker@gmail.com',
  phone: '+44781234122',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-023',
  firstName: 'Ryan',
  lastName: 'Evans',
  email: 'ryan.evans@gmail.com',
  phone: '+44781234123',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-024',
  firstName: 'Sophia',
  lastName: 'Turner',
  email: 'sophia.turner@gmail.com',
  phone: '+44781234124',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-025',
  firstName: 'Ethan',
  lastName: 'Edwards',
  email: 'ethan.edwards@gmail.com',
  phone: '+44781234125',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-026',
  firstName: 'Chloe',
  lastName: 'Collins',
  email: 'chloe.collins@gmail.com',
  phone: '+44781234126',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-027',
  firstName: 'Jack',
  lastName: 'Stevens',
  email: 'jack.stevens@gmail.com',
  phone: '+44781234127',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-028',
  firstName: 'Grace',
  lastName: 'Morris',
  email: 'grace.morris@gmail.com',
  phone: '+44781234128',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-029',
  firstName: 'Samuel',
  lastName: 'Rogers',
  email: 'samuel.rogers@gmail.com',
  phone: '+44781234129',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-030',
  firstName: 'Lily',
  lastName: 'Cook',
  email: 'lily.cook@gmail.com',
  phone: '+44781234130',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-031',
  firstName: 'Aaron',
  lastName: 'Reed',
  email: 'aaron.reed@gmail.com',
  phone: '+44781234131',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-032',
  firstName: 'Bella',
  lastName: 'Ward',
  email: 'bella.ward@gmail.com',
  phone: '+44781234132',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-033',
  firstName: 'Caleb',
  lastName: 'Peterson',
  email: 'caleb.peterson@gmail.com',
  phone: '+44781234133',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-034',
  firstName: 'Daisy',
  lastName: 'Gray',
  email: 'daisy.gray@gmail.com',
  phone: '+44781234134',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-035',
  firstName: 'Evan',
  lastName: 'Ramirez',
  email: 'evan.ramirez@gmail.com',
  phone: '+44781234135',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-036',
  firstName: 'Fiona',
  lastName: 'Barnes',
  email: 'fiona.barnes@gmail.com',
  phone: '+44781234136',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-037',
  firstName: 'Gavin',
  lastName: 'Hunt',
  email: 'gavin.hunt@gmail.com',
  phone: '+44781234137',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-038',
  firstName: 'Hannah',
  lastName: 'Stone',
  email: 'hannah.stone@gmail.com',
  phone: '+44781234138',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-039',
  firstName: 'Ian',
  lastName: 'Fox',
  email: 'ian.fox@gmail.com',
  phone: '+44781234139',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-040',
  firstName: 'Julia',
  lastName: 'Coleman',
  email: 'julia.coleman@gmail.com',
  phone: '+44781234140',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-041',
  firstName: 'Kyle',
  lastName: 'Simmons',
  email: 'kyle.simmons@gmail.com',
  phone: '+44781234141',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-042',
  firstName: 'Lara',
  lastName: 'Wells',
  email: 'lara.wells@gmail.com',
  phone: '+44781234142',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-043',
  firstName: 'Miles',
  lastName: 'Foster',
  email: 'miles.foster@gmail.com',
  phone: '+44781234143',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-044',
  firstName: 'Nina',
  lastName: 'Bryant',
  email: 'nina.bryant@gmail.com',
  phone: '+44781234144',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-045',
  firstName: 'Owen',
  lastName: 'Perry',
  email: 'owen.perry@gmail.com',
  phone: '+44781234145',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-046',
  firstName: 'Paula',
  lastName: 'Sanders',
  email: 'paula.sanders@gmail.com',
  phone: '+44781234146',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-047',
  firstName: 'Quinn',
  lastName: 'Price',
  email: 'quinn.price@gmail.com',
  phone: '+44781234147',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-048',
  firstName: 'Rita',
  lastName: 'Bennett',
  email: 'rita.bennett@gmail.com',
  phone: '+44781234148',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-049',
  firstName: 'Sean',
  lastName: 'Wood',
  email: 'sean.wood@gmail.com',
  phone: '+44781234149',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-050',
  firstName: 'Tina',
  lastName: 'West',
  email: 'tina.west@gmail.com',
  phone: '+44781234150',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-051',
  firstName: 'Uma',
  lastName: 'Young',
  email: 'uma.young@gmail.com',
  phone: '+44781234151',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-052',
  firstName: 'Victor',
  lastName: 'Diaz',
  email: 'victor.diaz@gmail.com',
  phone: '+44781234152',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-053',
  firstName: 'Wendy',
  lastName: 'Griffin',
  email: 'wendy.griffin@gmail.com',
  phone: '+44781234153',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-054',
  firstName: 'Xavier',
  lastName: 'Hayes',
  email: 'xavier.hayes@gmail.com',
  phone: '+44781234154',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-055',
  firstName: 'Yara',
  lastName: 'Myers',
  email: 'yara.myers@gmail.com',
  phone: '+44781234155',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-056',
  firstName: 'Zack',
  lastName: 'Ford',
  email: 'zack.ford@gmail.com',
  phone: '+44781234156',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-057',
  firstName: 'Alan',
  lastName: 'Hamilton',
  email: 'alan.hamilton@gmail.com',
  phone: '+44781234157',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-058',
  firstName: 'Bianca',
  lastName: 'Graham',
  email: 'bianca.graham@gmail.com',
  phone: '+44781234158',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-059',
  firstName: 'Carl',
  lastName: 'Sullivan',
  email: 'carl.sullivan@gmail.com',
  phone: '+44781234159',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-060',
  firstName: 'Diana',
  lastName: 'Russell',
  email: 'diana.russell@gmail.com',
  phone: '+44781234160',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-061',
  firstName: 'Eli',
  lastName: 'Ortiz',
  email: 'eli.ortiz@gmail.com',
  phone: '+44781234161',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-062',
  firstName: 'Faith',
  lastName: 'Jenkins',
  email: 'faith.jenkins@gmail.com',
  phone: '+44781234162',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-063',
  firstName: 'Gordon',
  lastName: 'Patterson',
  email: 'gordon.patterson@gmail.com',
  phone: '+44781234163',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-064',
  firstName: 'Hazel',
  lastName: 'Hughes',
  email: 'hazel.hughes@gmail.com',
  phone: '+44781234164',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-065',
  firstName: 'Isaac',
  lastName: 'Flores',
  email: 'isaac.flores@gmail.com',
  phone: '+44781234165',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-066',
  firstName: 'Jade',
  lastName: 'Washington',
  email: 'jade.washington@gmail.com',
  phone: '+44781234166',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-067',
  firstName: 'Kevin',
  lastName: 'Butler',
  email: 'kevin.butler@gmail.com',
  phone: '+44781234167',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-068',
  firstName: 'Lena',
  lastName: 'Snyder',
  email: 'lena.snyder@gmail.com',
  phone: '+44781234168',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-069',
  firstName: 'Martin',
  lastName: 'Simpson',
  email: 'martin.simpson@gmail.com',
  phone: '+44781234169',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-070',
  firstName: 'Nora',
  lastName: 'Porter',
  email: 'nora.porter@gmail.com',
  phone: '+44781234170',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-071',
  firstName: 'Oscar',
  lastName: 'Hunter',
  email: 'oscar.hunter@gmail.com',
  phone: '+44781234171',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-072',
  firstName: 'Paige',
  lastName: 'Gibson',
  email: 'paige.gibson@gmail.com',
  phone: '+44781234172',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-073',
  firstName: 'Quentin',
  lastName: 'Ellis',
  email: 'quentin.ellis@gmail.com',
  phone: '+44781234173',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-074',
  firstName: 'Rose',
  lastName: 'Fisher',
  email: 'rose.fisher@gmail.com',
  phone: '+44781234174',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-075',
  firstName: 'Steve',
  lastName: 'Reynolds',
  email: 'steve.reynolds@gmail.com',
  phone: '+44781234175',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-076',
  firstName: 'Tara',
  lastName: 'Jordan',
  email: 'tara.jordan@gmail.com',
  phone: '+44781234176',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-077',
  firstName: 'Ulysses',
  lastName: 'Lawson',
  email: 'ulysses.lawson@gmail.com',
  phone: '+44781234177',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-078',
  firstName: 'Vera',
  lastName: 'Warren',
  email: 'vera.warren@gmail.com',
  phone: '+44781234178',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-079',
  firstName: 'Will',
  lastName: 'Cole',
  email: 'will.cole@gmail.com',
  phone: '+44781234179',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
{
  id: 'user-id-080',
  firstName: 'Zoe',
  lastName: 'Hayward',
  email: 'zoe.hayward@gmail.com',
  phone: '+44781234180',
  status: 'Active',
  accounts: [
    { id: 'microsoft-us-001', name: 'Microsoft US', status: 'ACTIVE' },
    { id: 'google-ca-002', name: 'Google Canada', status: 'ACTIVE' },
  ],
},
];
